name: homalg
version: 2017.09.10
date: 10/09/2017
description: A homological algebra meta-package for computable Abelian categories

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "ToolsForHomalg"
      version: ">=2012.10.27"
      url: "http://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/homalg/
readme: http://homalg-project.github.io/homalg_project/homalg/README
packageinfo: http://homalg-project.github.io/homalg_project/homalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/homalg-2017.09.10/homalg-2017.09.10.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/homalg-2017.09.10/homalg-2017.09.10.zip

abstract: A homological algebra meta-package for computable Abelian categories

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
