## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "Modules" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "Modules", "doc" )[1]![1], "ModulesForHomalg.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "Modules" );
QUIT;
