#!/bin/bash

cd ..

# TODO: MapleForHomalg
PACKAGES_TO_CLONE="
test_suite
AbelianSystems
alcove
alexander
CAP_project
Conley
D-Modules
k-Points
Orbifolds
Sheaves
SimplicialObjects
SystemTheory
VirtualCAS
"

for PACKAGE in $PACKAGES_TO_CLONE; do
	if [ ! -e $PACKAGE ]; then
		git clone "https://github.com/homalg-project/$PACKAGE.git"
	fi
done

cp test_suite/init_homalg_project_test_suite.sample test_suite/init_homalg_project_test_suite
sed -i "s|~/software/pkg|$PWD|g" test_suite/init_homalg_project_test_suite

# remove tests already covered by ci-test
sed -i 's|homalg_project/[^ "]*||g' test_suite/test_packages_of_homalg_project

cd homalg_project
