## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "HomalgToCAS" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "HomalgToCAS", "doc" )[1]![1], "HomalgToCAS.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "HomalgToCAS" );
QUIT;
