mrel :=MatrixOfRelations( M );
mbas := BasisOfRowsCoeff( mrel );
U := RightHandSide( mbas );
Print( Eval( U * mrel - mbas ), "\n" );
nrel := MatrixOfRelations( N );
nbas := BasisOfColumnsCoeff( nrel );
V := BottomSide( nbas );
Print( Eval( nrel * V - nbas ), "\n" );
gen1 := CreateGeneratorsForLeftModule( [[1,0,0],[0,1,0]], R );
gen2 := CreateGeneratorsForLeftModule( [[0,0,0]], R );
gen1/gen2;
gen3 := CreateGeneratorsForLeftModule(SyzygiesGeneratorsOfRows(MatrixOfGenerators(gen1),[]));
gen4:=CreateGeneratorsForLeftModule( [[0,0]], R );
gen3/gen4;
