mrel :=MatrixOfRelations( M );
mbas := BasisOfRowsCoeff( mrel );
U := RightHandSide( mbas );
Print( Eval( U * mrel - mbas ), "\n" );
nrel := MatrixOfRelations( N );
nbas := BasisOfColumnsCoeff( nrel );
V := BottomSide( nbas );
Print( Eval( nrel * V - nbas ), "\n" );
kk1 := [[1,0,0],[0,1,0]];
kk2 := [[0,0,0]];
kk3 := [[0,0]];
gen1 := HomalgGeneratorsForLeftModule( kk1, R );
gen2 := HomalgGeneratorsForLeftModule( kk2, R );
gen1/gen2;
gen3 := HomalgGeneratorsForLeftModule(SyzygiesBasisOfRows(MatrixOfGenerators(gen1)));
gen4:=HomalgGeneratorsForLeftModule( kk3, R );
gen3/gen4;
neg1 := HomalgGeneratorsForRightModule( TransposedMat( kk1 ), R );
neg2 := HomalgGeneratorsForRightModule( TransposedMat( kk2 ), R );
neg1/neg2;
neg3 := HomalgGeneratorsForRightModule(SyzygiesBasisOfColumns(MatrixOfGenerators(neg1)));
neg4:=HomalgGeneratorsForRightModule( TransposedMat( kk3 ), R );
neg3/neg4;
