name: 4ti2Interface
version: 2017.09.01
date: 01/09/2017
description: A link to 4ti2

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

GAP: ">=4.7"

needed-pkgs:
    - name: "io"
      version: ">=4.2"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "AutoDoc"
      version: ">=2013.08.22"
      url: "https://gap-packages.github.io/AutoDoc"

www: http://homalg-project.github.io/homalg_project/4ti2Interface/
readme: http://homalg-project.github.io/homalg_project/4ti2Interface/README
packageinfo: http://homalg-project.github.io/homalg_project/4ti2Interface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/4ti2Interface-2017.09.01/4ti2Interface-2017.09.01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/4ti2Interface-2017.09.01/4ti2Interface-2017.09.01.zip

abstract: The <span class="pkgname">4ti2Interface</span> package provides an interface to 4ti2

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
