name: GradedRingForHomalg
version: 2017.09.01
date: 01/09/2017
description: Endow Commutative Rings with an Abelian Grading

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Markus Kirschmer
      url: http://www.math.rwth-aachen.de/~Markus.Kirschmer/
    - name: Sebastian Jambor
      url: http://wwwb.math.rwth-aachen.de/~sebastian/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/
    - name: Daniel Robertz
      url: http://wwwb.math.rwth-aachen.de/~daniel/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">= 2014.08.26"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2013.07.14"
      url: "http://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "RingsForHomalg"
      version: ">= 2013.07.14"
      url: "http://homalg-project.github.io/homalg_project/RingsForHomalg/"
    - name: "Modules"
      version: ">= 2011.09.20"
      url: "http://homalg-project.github.io/homalg_project/Modules/"
    - name: "homalg"
      version: ">=2011.08.16"
      url: "http://homalg-project.github.io/homalg_project/homalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/GradedRingForHomalg/
readme: http://homalg-project.github.io/homalg_project/GradedRingForHomalg/README
packageinfo: http://homalg-project.github.io/homalg_project/GradedRingForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/GradedRingForHomalg-2017.09.01/GradedRingForHomalg-2017.09.01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/GradedRingForHomalg-2017.09.01/GradedRingForHomalg-2017.09.01.zip

abstract: This package is part of the homalg-project and manages graded rings.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
