## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "Gauss" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "Gauss", "doc" )[1]![1], "Gauss.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "Gauss" );
QUIT;
