## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "SCO" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "SCO", "doc" )[1]![1], "SCO.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "SCO" );
QUIT;
