name: Modules
version: 2018.08.24
date: 24/08/2018
description: A homalg based package for the Abelian category of finitely presented modules over computable rings

authors:
    - name: Thomas Bächler
      url: http://wwwb.math.rwth-aachen.de/~thomas/
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Florian Diebold
      url: mailto:diebold@mathematik.uni-kl.de
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/
    - name: Vinay Wagh
      url: http://www.iitg.ernet.in/vinay.wagh/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">=2018.08.01"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "ToolsForHomalg"
      version: ">=2013.04.12"
      url: "http://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "homalg"
      version: ">=2017.03.18"
      url: "http://homalg-project.github.io/homalg_project/homalg/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/Modules/
readme: http://homalg-project.github.io/homalg_project/Modules/README
packageinfo: http://homalg-project.github.io/homalg_project/Modules/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/Modules-2018.08.24/Modules-2018.08.24.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/Modules-2018.08.24/Modules-2018.08.24.zip

abstract: The <span class="pkgname">Modules</span> package provides ring independent homological algebra functionality for the abelian category of finitely presented modules over computable rings

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
